[[news]]
date = "2026.06"
content = "Invited for an oral presentation and poster exhibition at the Associated Professional Sleep Societies (SLEEP 2026), Baltimore, USA."

[[news]]
date = "2025.09"
content = "Received the Asian Society of Sleep Medicine (ASSM 2025) Young Investigator Award in Singapore."

[[news]]
date = "2025.09"
content = "Invited for an oral presentation and presented posters at the 18th World Sleep Congress, Singapore."