[[news]]
date = "2026.06"
content = "受邀在 美国睡眠医学会年会（SLEEP 2026，美国巴尔的摩）进行口头报告和壁报展示。"

[[news]]
date = "2025.09"
content = "获得 亚洲睡眠协会（ASSM）2025年度青年研究者奖，新加坡。"

[[news]]
date = "2025.09"
content = "受邀在第 18 届 世界睡眠大会（World Sleep 2025，新加坡）进行口头报告并展示壁报。"